name: toro_models
description: Up to date library for keeping toro models consistant.

version: 0.5.1

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  hive: ^1.4.1+1
  json_annotation: ^3.0.1

dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
